// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"book/internal/biz"
	"book/internal/conf"
	"book/internal/data"
	"book/internal/server"
	"book/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	// greeterRepo := data.NewGreeterRepo(dataData, logger)
	// greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	// greeterService := service.NewGreeterService(greeterUsecase)
	bookRepo := data.NewBookRepo(dataData, logger)
	bookUsecase := biz.NewBookUsecase(bookRepo, logger)
	bookService := service.NewBookService(bookUsecase)
	grpcServer := server.NewBookGRPCServer(confServer, bookService, logger)
	httpServer := server.NewBookHTTPServer(confServer, bookService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
